/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesIdRouteImport } from './routes/actualites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIdRoute = ActualitesIdRouteImport.update({
  id: '/actualites/$id',
  path: '/actualites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites': typeof ActualitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evenements' | '/actualites/$id' | '/actualites/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evenements' | '/actualites/$id' | '/actualites'
  id: '__root__' | '/' | '/evenements' | '/actualites/$id' | '/actualites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvenementsRoute: typeof EvenementsRoute
  ActualitesIdRoute: typeof ActualitesIdRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$id': {
      id: '/actualites/$id'
      path: '/actualites/$id'
      fullPath: '/actualites/$id'
      preLoaderRoute: typeof ActualitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvenementsRoute: EvenementsRoute,
  ActualitesIdRoute: ActualitesIdRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
